Repository carpentries/amy, pull requests merged in 2018-11, with the labels that each got.

#1390 Admin notifications propagation to various emails
  amy/settings.py
  extforms/views.py
  workshops/base_views.py
  workshops/test/test_util.py
  workshops/test/test_workshop_requests.py
  workshops/util.py
Labels: component: user interface (UI), type: new feature

#1391 Add instructor training seat details to Organization details page
  workshops/templates/workshops/organization.html
Labels: component: user interface (UI)

#1393 adding LC description to Request a Workshop page
  workshops/models.py
Labels: component: user interface (UI)

#1396 Fix PersonViewSet queryset to include only distinct results
  api/views.py
Labels: component: API, type: bug

#1398 Warning for trainings falling out of agreement dates
  amy/extrequests/views.py
  amy/workshops/views.py
Labels: component: user interface (UI)

#1399 Lesson publication consent
  amy/api/serializers.py
  amy/dashboard/forms.py
  amy/templates/workshops/person.html
  amy/workshops/forms.py
  amy/workshops/migrations/0165_person_lesson_publication_consent.py
  amy/workshops/models.py
Labels: component: API, component: database (DB), component: user interface (UI), type: enhancement

#1400 New ITT, LSO, LMO tags
  amy/dashboard/views.py
  amy/templates/dashboard/admin_dashboard.html
  amy/templates/includes/curriculum.html
  amy/templates/includes/event_details_table.html
  amy/templates/includes/tag.html
  amy/templates/reports/instructors_by_date.html
  amy/templates/requests/all_workshoprequests.html
  amy/templates/workshops/all_events.html
  amy/templates/workshops/events_merge.html
  amy/workshops/migrations/0166_new_tags_ITT_LMO_LSO.py
  amy/workshops/models.py
  amy/workshops/templatetags/tags.py
Labels: component: database (DB), component: user interface (UI)

#1411 Remove admin fee, invoice fields
  amy/api/serializers.py
  amy/templates/includes/event_details_table.html
  amy/workshops/forms.py
  amy/workshops/tests/test_event.py
Labels: component: API, component: user interface (UI), status: needs feedback

#1402 Add library carpentry links to confirmation pages
  amy/templates/forms/trainingrequest_confirm.html
  amy/templates/forms/workshoprequest_confirm.html
Labels: component: user interface (UI)

#1413 Fix bulk upload server error
  amy/workshops/tests/test_bulk_add.py
  amy/workshops/util.py
Labels: priority: essential, type: bug

#1414 Force encoding for languages registry (used in migrations)
  amy/workshops/migrations/0097_auto_20160519_0739.py
  amy/workshops/migrations/0139_fix_language_names.py
Labels: type: bug
