Repository carpentries/amy, pull requests merged in 2018-05, with the labels that each got.

#1239 Redirect `/` to `/workshops`
  amy/urls.py
  workshops/test/test_security.py
Labels: type: bug

#1238 Fix profile update request accept (#1237)
  workshops/test/test_profile_update_request.py
  workshops/views.py
Labels: type: bug

#1234 fix for TrainingRequest in Fake Database
  workshops/management/commands/fake_database.py
Labels: type: bug

#1241 Adding badges to track mentorship participation
  workshops/migrations/0134_mentor_mentee_badges.py
Labels: component: database, type: enhancement

#1251 GDPR: publish profile option for users
  Makefile
  amy/settings.py
  api/filters.py
  api/serializers.py
  api/test/test_export.py
  api/views.py
  workshops/forms.py
  workshops/management/commands/fake_database.py
  workshops/migrations/0135_auto_20180519_1403.py
  workshops/migrations/0136_auto_20180524_1042.py
  workshops/models.py
  workshops/templates/workshops/person.html
  workshops/templates/workshops/persons_merge.html
  workshops/templates/workshops/trainee_dashboard.html
  workshops/test/test_person.py
  workshops/test/test_util.py
  workshops/util.py
  workshops/views.py
Labels: component: database, component: law compliance, component: user interface, priority: essential, status: needs improvements

#1253 Repair M2M merging bug that removed `SWC` tag from AMY
  workshops/test/test_event.py
  workshops/util.py
Labels: component: database, priority: essential, type: bug

#1254 Privacy consent from users
  amy/settings.py
  api/test/test_api_structure.py
  api/test/test_export.py
  api/test/test_reports.py
  workshops/action_required.py
  workshops/forms.py
  workshops/migrations/0137_auto_20180524_1228.py
  workshops/migrations/0138_auto_20180524_1400.py
  workshops/models.py
  workshops/templates/base_nonav_fixed.html
  workshops/templates/workshops/action_required_privacy.html
  workshops/templates/workshops/person.html
  workshops/templates/workshops/persons_merge.html
  workshops/test/base.py
  workshops/test/test_action_required.py
  workshops/test/test_autoupdate_profile.py
  workshops/test/test_landing_page.py
  workshops/test/test_person.py
  workshops/test/test_security.py
  workshops/test/test_trainee_dashboard.py
  workshops/urls.py
  workshops/views.py
Labels: component: database, component: user interface

#1259 Fix double instructors in API
  api/test/test_export.py
  api/views.py
Labels: component: API

#1258 Fix Select2 widget not being loaded
  workshops/static/amy_utils.js
Labels: component: user interface, type: bug
