Repository carpentries/amy, pull requests merged in 2018-10, with the labels that each got.

#1361 Default ordering on Languages by name
  workshops/migrations/0157_auto_20181006_0859.py
  workshops/models.py
Labels: component: user interface (UI)

#1362 BulkMatchTrainingRequestForm: "open seat" field
  workshops/forms.py
  workshops/views.py
Labels: component: user interface (UI), priority: essential

#1363 Events API: Fix 500-error when filtering
  api/filters.py
  workshops/models.py
Labels: component: API, priority: essential, type: bug

#1364 `Country` field in Persons, Events, Events Published APIs
  api/filters.py
  api/serializers.py
  api/views.py
Labels: component: API

#1372 Upgrade Python, JS, CSS dependencies to the latest versions
  requirements.txt
  yarn.lock
Labels: component: deployment

#1373 Disable profile update requests
  extforms/urls.py
  extforms/views.py
  workshops/templates/forms/profileupdate.html
  workshops/templates/forms/profileupdate_confirm.html
  workshops/templates/includes/eventsubmission.html
  workshops/templates/mailing/eventsubmission.txt
  workshops/templates/mailing/profileupdaterequest.html
  workshops/templates/mailing/profileupdaterequest.txt
  workshops/templates/workshops/all_profileupdaterequests.html
  workshops/templates/workshops/eventsubmission.html
  workshops/templates/workshops/eventsubmission_accept_event.html
  workshops/test/test_action_required.py
  workshops/test/test_profile_update_request.py
Labels: component: user interface (UI), type: maintenance, type: refactoring

#1374 Bulk upload training request manual score
  api/renderers.py
  api/serializers.py
  api/test/test_trainingrequests.py
  api/views.py
  workshops/forms.py
  workshops/models.py
  workshops/static/amy_utils.js
  workshops/templates/navigation.html
  workshops/templates/workshops/all_trainingrequests.html
  workshops/templates/workshops/trainingrequest_bulk_upload_manual_score_confirmation.html
  workshops/templates/workshops/trainingrequest_bulk_upload_manual_score_form.html
  workshops/test/test_bulk_manual_score.py
  workshops/urls.py
  workshops/util.py
  workshops/views.py
Labels: component: API, component: user interface (UI), type: new feature

#1376 Revert Django-Autocomplete-Light due to buggy widget display
  requirements.txt
Labels: type: revert

#1380 Memberships filter: fix bug in filter method name & logic
  workshops/filters.py
Labels: component: user interface (UI), type: bug

#1381 Instructor badges display bug
  api/serializers.py
  api/views.py
  workshops/templates/workshops/event.html
  workshops/views.py
Labels: component: database (DB), component: user interface (UI), type: bug

#1366 Update readme
  README.md
Labels: Getting started, component: documentation, type: bug

#1382 Submit buttons on form tops
  workshops/forms.py
  workshops/templates/bootstrap4/whole_uni_form.html
Labels: component: user interface (UI)

#1386 Training Requests list refinements
  workshops/templates/workshops/all_trainingrequests.html
Labels: component: user interface (UI), type: enhancement
