Repository carpentries/amy, pull requests merged in 2019-01, with the labels that each got.

#1438 Workshop request list: comment column with missing comments
  amy/extrequests/tests/test_workshop_requests.py
  amy/templates/requests/all_workshoprequests.html
Labels: Getting started, component: user interface (UI), priority: essential, type: bug

#1439 Fix #1437: MembershipForm triggering comment creation w/o comment field
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
Labels: priority: essential, type: bug

#1440 Update Travis config to work with Python 3.7
  .travis.yml
Labels: component: deployment

#1441 Update procedures.md
  Makefile
  docs/procedures.md
  package.json
Labels: component: documentation

#1445 Application group code
  amy/api/renderers.py
  amy/api/tests/test_trainingrequests.py
  amy/templates/requests/all_trainingrequests.html
  amy/templates/requests/trainingrequest.html
  amy/templates/requests/trainingrequests_merge.html
  amy/workshops/migrations/0176_auto_20190115_1542.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), type: enhancement

#1449 updated email addresses
  amy/templates/forms/trainingrequest.html
Labels: component: user interface (UI)

#1452 Travis: fix broken migration testing command
  .travis.yml
Labels: type: bug

#1453 Remove InvoiceRequests, ProfileUpdateRequests
  amy/extforms/deprecated_forms.py
  amy/extrequests/deprecated_filters.py
  amy/extrequests/deprecated_forms.py
  amy/extrequests/deprecated_views.py
  amy/extrequests/migrations/0002_auto_20190130_0839.py
  amy/extrequests/models.py
  amy/extrequests/tests/test_invoice_requests.py
  amy/extrequests/tests/test_profile_update_request.py
  amy/extrequests/urls.py
  amy/templates/navigation.html
  amy/templates/requests_deprecated/all_invoicerequests.html
  amy/templates/requests_deprecated/all_profileupdaterequests.html
  amy/templates/requests_deprecated/invoicerequest.html
  amy/templates/requests_deprecated/profileupdaterequest.html
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0177_auto_20190130_0815.py
  amy/workshops/models.py
  config/urls.py
  docs/design/database_models.md
  docs/models_in_applications.md
Labels: component: database (DB), component: documentation

#1454 Search in comments
  amy/templates/workshops/search.html
  amy/workshops/forms.py
  amy/workshops/tests/test_search.py
  amy/workshops/views.py
Labels: type: new feature

#1456 fix location of git_version.py
  Makefile
Labels: component: deployment, type: bug

#1458 Membership details: Display badges for each instructor training seat
  amy/fiscal/views.py
  amy/templates/fiscal/membership.html
Labels: component: user interface (UI), type: enhancement
