Repository carpentries/amy, pull requests merged in 2019-09, with the labels that each got.

#1524 Upgrade Django to v2.2.4
  .travis.yml
  README.md
  amy/api/views.py
  amy/dashboard/views.py
  amy/extrequests/tests/test_training_request.py
  amy/fiscal/tests/test_organization.py
  amy/reports/views.py
  amy/trainings/views.py
  amy/workshops/fields.py
  amy/workshops/filters.py
  amy/workshops/lookups.py
  amy/workshops/migrations/0084_lowercase_emails.py
  amy/workshops/migrations/0097_auto_20160519_0739.py
  amy/workshops/migrations/0139_fix_language_names.py
  amy/workshops/migrations/0140_NullableGithubUsernameField.py
  amy/workshops/migrations/0178_auto_20190213_1640.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_event.py
  amy/workshops/views.py
  requirements.txt
Labels: component: deployment, component: security, type: maintenance

#1514 Additional option for Lesson Publication Consent
  amy/workshops/migrations/0185_revamp_lesson_publication_consent.py
  amy/workshops/models.py
Labels: component: database (DB)

#1518 fix #1517 - login page for admins/instructors
  amy/templates/account/login.html
Labels: component: user interface (UI)

#1528 Add Chemistry to auto scored domains for Instructor Training Requests
  amy/extrequests/tests/test_training_request.py
  amy/workshops/models.py
Labels: type: enhancement

#1529 Add lesson publication consent to Trainee Dashboard
  amy/templates/dashboard/trainee_dashboard.html
Labels: component: user interface (UI)

#1530 fix typo
  amy/templates/workshops/person.html
Labels: component: user interface (UI)

#1531 change GH link swcarpentry > carpentries
  amy/templates/base.html
Labels: component: user interface (UI)

#1533 Training request review process field
  amy/extforms/forms.py
  amy/extforms/tests/test_training_request_form.py
  amy/extrequests/tests/test_training_request.py
  amy/templates/forms/trainingrequest.html
  amy/workshops/migrations/0204_trainingrequest_review_process.py
  amy/workshops/models.py
Labels: component: user interface (UI), type: enhancement

#1542 Update repository links in procedures.md
  docs/procedures.md
Labels: component: documentation, type: bug

#1543 Add missing pagination on All Workshop Inquiries and Self-Organised Submissions
  amy/templates/requests/all_selforganisedsubmissions.html
  amy/templates/requests/all_workshopinquiries.html
Labels: component: user interface (UI), type: bug

#1544 Widen admin-selection widget
  amy/workshops/forms.py
Labels: component: user interface (UI), type: bug

#1546 Fix wrong permissions in `extrequests.views`
  amy/extrequests/views.py
Labels: type: bug

#1547 Add missing fields to WorkshopRequest->SelfOrganisedSubmission migration
  amy/extrequests/migrations/0006_migrate_workshop_requests_to_selforg_submissions.py
Labels: component: database (DB), component: deployment, type: bug

#1545 Enable cache
  config/settings.py
Labels: component: user interface (UI), type: bug

#1548 Add 'review_process' to CSV download of Training Requests data
  amy/api/renderers.py
  amy/api/serializers.py
  amy/api/tests/test_export.py
  amy/api/tests/test_trainingrequests.py
Labels: component: API, component: user interface (UI), type: enhancement

#1553 Fix invalid permission passed to action widget
  amy/templates/requests/selforganisedsubmission.html
  amy/templates/requests/workshopinquiry.html
Labels: component: user interface (UI), type: bug

#1552 Fix assignment link in SelfOrgSubmission and WorkshopInquiry
  amy/templates/requests/selforganisedsubmission.html
  amy/templates/requests/workshopinquiry.html
Labels: component: user interface (UI), type: bug
