Repository carpentries/amy, pull requests merged in 2019-12, with the labels that each got.

#1582 Fix change_workshopinquiry permission name
  amy/extrequests/views.py
Labels: component: database (DB), type: bug

#1592 Update to Django v2.2.9
  requirements.txt
Labels: component: deployment

#1590 Readme instructions to createcachetable
  README.md
Labels: component: documentation

#1585 fix link to teaching demo etherpad
  amy/templates/dashboard/training_progress.html
Labels: component: user interface (UI), type: bug

#1594 Trainer badge in badge column on all persons / event details / workshop staff pages
  amy/static/css/amy.css
  amy/templates/workshops/all_persons.html
  amy/templates/workshops/event.html
  amy/templates/workshops/workshop_staff.html
  amy/workshops/models.py
  amy/workshops/tests/test_workshop_staff_searching.py
  amy/workshops/views.py
Labels: component: user interface (UI), type: enhancement

#1595 Enable responsiveness on login page
  amy/templates/account/base.html
  amy/templates/account/login.html
Labels: component: user interface (UI), type: bug

#1597 Additional gender choices
  amy/api/serializers.py
  amy/dashboard/forms.py
  amy/extforms/forms.py
  amy/extrequests/forms.py
  amy/templates/dashboard/trainee_dashboard.html
  amy/templates/workshops/person.html
  amy/templates/workshops/persons_merge.html
  amy/workshops/forms.py
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0205_auto_20191230_1406.py
  amy/workshops/models.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_person.py
  amy/workshops/views.py
Labels: component: database (DB), component: user interface (UI), type: enhancement

#1599 Secondary email field
  amy/api/renderers.py
  amy/api/serializers.py
  amy/api/tests/test_export.py
  amy/api/tests/test_trainingrequests.py
  amy/dashboard/forms.py
  amy/extforms/forms.py
  amy/extforms/tests/test_selforganised_submission_form.py
  amy/extforms/tests/test_workshop_inquiry_form.py
  amy/extforms/tests/test_workshop_request_form.py
  amy/extrequests/forms.py
  amy/extrequests/migrations/0018_auto_20191231_0958.py
  amy/extrequests/tests/test_training_request.py
  amy/extrequests/views.py
  amy/templates/dashboard/trainee_dashboard.html
  amy/templates/requests/trainingrequests_merge.html
  amy/templates/workshops/person.html
  amy/templates/workshops/persons_merge.html
  amy/workshops/forms.py
  amy/workshops/lookups.py
  amy/workshops/migrations/0206_auto_20191231_0958.py
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
  amy/workshops/views.py
Labels: component: database (DB), component: user interface (UI), type: enhancement

#1600 Django-Compressor performance upgrade
  config/settings.py
  requirements.txt
Labels: component: database (DB), component: deployment, type: bug
