Repository carpentries/amy, pull requests merged in 2020-01, with the labels that each got.

#1596 Additional contact - styling, field widget bugs
  amy/extrequests/migrations/0018_auto_20191230_1113.py
  amy/templates/includes/selforganisedsubmission_details.html
  amy/templates/includes/workshopinquiry_details.html
  amy/templates/includes/workshoprequest_details.html
  amy/workshops/fields.py
  amy/workshops/management/commands/fake_database.py
Labels: component: database (DB), component: user interface (UI), type: bug

#1602 Update WorkshopInquiryRequest's assignment view
  amy/extrequests/views.py
Labels: type: bug

#1593 LC instructor trainees - improvements for trainee search
  amy/dashboard/tests/test_trainee_dashboard.py
  amy/templates/trainings/all_trainees.html
  amy/trainings/filters.py
  amy/trainings/tests/test_trainees.py
  amy/trainings/views.py
  amy/workshops/filters.py
  amy/workshops/migrations/0205_auto_20191229_1801.py
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
Labels: component: database (DB), component: user interface (UI), priority: essential, type: bug

#1603 Tags: add priority field
  amy/workshops/admin.py
  amy/workshops/migrations/0208_auto_20200110_1103.py
  amy/workshops/migrations/0209_auto_20200110_1154.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), type: enhancement, type: new feature

#1604 Upgrade some dependencies due to deprecation warnings in old versions
  amy/api/urls.py
  amy/workshops/util.py
  requirements.txt
Labels: component: deployment, component: security, dependencies, type: bug, type: maintenance

#1606 Send form copy to Training Request applicant
  amy/extforms/tests/test_training_request_form.py
  amy/templates/includes/trainingrequest_details.html
  amy/templates/mailing/training_request.html
  amy/templates/mailing/training_request.txt
  amy/templates/requests/trainingrequest.html
  amy/workshops/management/commands/fake_database.py
Labels: component: user interface (UI), type: enhancement

#1611 add link to submit self org wkshp
  amy/templates/dashboard/trainee_dashboard.html
Labels: component: user interface (UI), type: enhancement

#1613 Event form - restricting administrator field
  amy/workshops/forms.py
  amy/workshops/lookups.py
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0210_auto_20200124_1939.py
  amy/workshops/models.py
  amy/workshops/tests/test_event.py
Labels: component: database (DB), component: user interface (UI), type: enhancement
