Repository carpentries/amy, pull requests merged in 2020-05, with the labels that each got.

#1649 Add list of event tags to email body
  amy/autoemails/actions.py
  amy/autoemails/tests/test_newinstructoraction.py
  amy/autoemails/tests/test_postworkshopaction.py
  amy/autoemails/tests/test_selforganisedrequestaction.py
Labels: component: email automation, type: enhancement

#1652 Fix Select2TagWidget error when value is empty list
  amy/workshops/fields.py
  amy/workshops/tests/test_fields.py
Labels: priority: essential, type: bug

#1660 Add form prefixes to Award create and Task create forms
  amy/workshops/forms.py
  amy/workshops/tests/test_badge.py
  amy/workshops/tests/test_event.py
  amy/workshops/tests/test_person.py
  amy/workshops/tests/test_tasks.py
  amy/workshops/views.py
Labels: component: user interface (UI), type: bug

#1658 add links to online workshop resources to WRF automated emails
  amy/templates/mailing/selforganisedsubmission.html
  amy/templates/mailing/selforganisedsubmission.txt
  amy/templates/mailing/workshopinquiry.html
  amy/templates/mailing/workshopinquiry.txt
  amy/templates/mailing/workshoprequest.html
  amy/templates/mailing/workshoprequest.txt
Labels: type: bug

#1661 Improve syntax of some files, add linting options
  .flake8
  .gitignore
  amy/autoemails/actions.py
  amy/autoemails/forms.py
  amy/autoemails/mixins.py
  amy/autoemails/models.py
  amy/autoemails/tests/test_action.py
  amy/autoemails/utils.py
  amy/extrequests/models.py
  amy/workshops/forms.py
  amy/workshops/mixins.py
  amy/workshops/models.py
  amy/workshops/tests/test_badge.py
  amy/workshops/tests/test_event.py
  amy/workshops/tests/test_person.py
  amy/workshops/util.py
  amy/workshops/views.py
Labels: type: maintenance, type: refactoring

#1662 include redis/docker instructions in local setup
  README.md
Labels: component: documentation

#1667 Fix wrong permissions app name
  amy/extrequests/views.py
Labels: type: bug
