Repository carpentries/amy, pull requests merged in 2020-06, with the labels that each got.

#1663 make Administrator field required
  amy/extrequests/tests/test_dc_selforganized_event_requests.py
  amy/extrequests/tests/test_event_requests.py
  amy/extrequests/tests/test_event_submissions.py
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/extrequests/tests/test_workshop_inquiries.py
  amy/extrequests/tests/test_workshop_requests.py
  amy/workshops/forms.py
  amy/workshops/tests/test_event.py
Labels: type: enhancement, type: refactoring

#1671 Search by person's secondary email
  amy/workshops/tests/test_search.py
  amy/workshops/views.py
Labels: python, type: enhancement

#1672 Revert removal of comment box for Event Update
  amy/workshops/views.py
Labels: component: user interface (UI), type: bug

#1670 Instructors and host introduction - email automation
  amy/autoemails/actions.py
  amy/autoemails/base_views.py
  amy/autoemails/fixtures/templates_triggers.json
  amy/autoemails/migrations/0010_auto_20200517_1803.py
  amy/autoemails/models.py
  amy/autoemails/tests/test_instructorshostintroductionaction.py
  amy/autoemails/tests/test_selforganisedrequestaction.py
  amy/extrequests/views.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_event.py
  amy/workshops/tests/test_tasks.py
  amy/workshops/util.py
  amy/workshops/views.py
Labels: component: email automation, python, type: new feature

#1674 Confirming supporting instructor
  amy/autoemails/actions.py
  amy/autoemails/fixtures/templates_triggers.json
  amy/autoemails/migrations/0011_auto_20200620_2055.py
  amy/autoemails/models.py
  amy/autoemails/tests/test_newsupportinginstructoraction.py
  amy/workshops/tests/test_tasks.py
  amy/workshops/util.py
  amy/workshops/views.py
Labels: component: database (DB), component: email automation, python, type: new feature

#1665 removes git_version.py
  .gitignore
  Makefile
  amy/templates/base.html
  amy/workshops/context_processors.py
  amy/workshops/git_version.py
  docs/procedures.md
Labels: type: maintenance

#1675 Hide "Lessons covered" from SOS mix&match event accept form
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/extrequests/views.py
Labels: component: email automation, type: enhancement
