Repository carpentries/amy, pull requests merged in 2020-04, with the labels that each got.

#1632 Regression fix: Instructors Over Time, badge not iterable
  amy/api/filters.py
  amy/api/tests/test_reports.py
Labels: component: API, type: bug

#1631 Update from URL when `slug` is missing
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/extrequests/views.py
  amy/workshops/management/commands/check_for_workshop_websites_updates.py
  amy/workshops/tests/test_util.py
  amy/workshops/util.py
  amy/workshops/views.py
Labels: component: user interface (UI), javascript, type: bug

#1634 Add instructors to PostWorkshopAction context
  amy/autoemails/actions.py
  amy/autoemails/tests/test_postworkshopaction.py
Labels: component: email automation, type: enhancement

#1636 Upgrade social-auth-core dependency
  requirements.txt
Labels: dependencies, python, type: maintenance

#1637 PostWorkshopAction: link to survey results
  amy/autoemails/actions.py
  amy/autoemails/tests/test_postworkshopaction.py
  amy/workshops/tests/test_util.py
  amy/workshops/util.py
  config/settings.py
Labels: component: email automation, python, type: enhancement

#1638 help text for self org. online workshop slug
  amy/extrequests/migrations/0019_auto_20200413_1724.py
  amy/extrequests/models.py
Labels: component: database (DB), component: user interface (UI), type: enhancement

#1633 PostWorkshopAction in "accept and create event" views
  amy/extrequests/base_views.py
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/extrequests/tests/test_workshop_inquiries.py
  amy/extrequests/tests/test_workshop_requests.py
  amy/extrequests/urls.py
  amy/extrequests/views.py
  amy/workshops/base_views.py
Labels: component: email automation, type: enhancement, type: refactoring

#1639 Job status, Django admin UI changes
  .dockerignore
  .gitignore
  amy/autoemails/actions.py
  amy/autoemails/admin.py
  amy/autoemails/base_views.py
  amy/autoemails/job.py
  amy/autoemails/templates/admin/autoemails/RQJob/change_list_object_tools.html
  amy/autoemails/templates/rqjob_preview.html
  amy/autoemails/tests/test_admin_cancel.py
  amy/autoemails/tests/test_newinstructoraction.py
  amy/autoemails/tests/test_postworkshopaction.py
  amy/autoemails/tests/test_selforganisedrequestaction.py
  amy/autoemails/tests/test_utils.py
  amy/autoemails/utils.py
  amy/static/css/rqjob_admin.css
  config/settings.py
  pyproject.toml
Labels: component: email automation, component: user interface (UI), type: new feature

#1643 Add ?next= param for GitHub login
  amy/templates/account/login.html
Labels: component: user interface (UI), type: bug

#1642 Contact meta tag - split by |
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/fiscal/forms.py
  amy/static/edit_from_url.js
  amy/templates/includes/event_details_table.html
  amy/templates/includes/workshoprequest_details.html
  amy/workshops/forms.py
  amy/workshops/templatetags/utils.py
  amy/workshops/tests/test_commands.py
  amy/workshops/tests/test_util.py
  amy/workshops/util.py
  amy/workshops/views.py
Labels: component: user interface (UI), type: bug, type: new feature
