Repository carpentries/amy, pull requests merged in 2020-10, with the labels that each got.

#1725 Ask For Website + RecruitHelpers logic change
  amy/autoemails/actions.py
  amy/autoemails/tests/test_askforwebsiteaction.py
  amy/autoemails/tests/test_recruithelpersaction.py
  amy/workshops/tests/test_event.py
  amy/workshops/tests/test_tasks.py
Labels: type: bug

#1721 Supporting Instructor role count
  amy/templates/workshops/person.html
  amy/workshops/views.py
Labels: component: user interface (UI), type: enhancement

#1726 Workshop public - a new field
  amy/templates/includes/event_details_table.html
  amy/workshops/forms.py
  amy/workshops/migrations/0220_event_public_status.py
  amy/workshops/models.py
Labels: component: user interface (UI), type: enhancement

#1729 Fix security issues found with CodeQL
  amy/extrequests/deprecated_forms.py
  amy/extrequests/migrations/0024_auto_20201025_1113.py
  amy/static/jquery-ui-custom/images/ui-bg_glass_55_fbf9ee_1x400.png
  amy/static/jquery-ui-custom/images/ui-bg_glass_65_ffffff_1x400.png
  amy/static/jquery-ui-custom/images/ui-bg_glass_75_dadada_1x400.png
  amy/static/jquery-ui-custom/images/ui-bg_glass_75_e6e6e6_1x400.png
  amy/static/jquery-ui-custom/images/ui-bg_glass_95_fef1ec_1x400.png
  amy/static/jquery-ui-custom/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  amy/static/jquery-ui-custom/images/ui-icons_222222_256x240.png
  amy/static/jquery-ui-custom/images/ui-icons_2e83ff_256x240.png
  amy/static/jquery-ui-custom/images/ui-icons_454545_256x240.png
  amy/static/jquery-ui-custom/images/ui-icons_888888_256x240.png
  amy/static/jquery-ui-custom/images/ui-icons_cd0a0a_256x240.png
  amy/static/jquery-ui-custom/jquery-ui.css
  amy/static/jquery-ui-custom/jquery-ui.js
  amy/static/jquery-ui-custom/jquery-ui.min.css
  amy/static/jquery-ui-custom/jquery-ui.min.js
  amy/templates/dashboard/trainee_dashboard.html
  amy/templates/fiscal/all_organizations.html
  amy/templates/fiscal/organization.html
  amy/templates/forms/trainingrequest.html
  amy/templates/includes/event_details_table.html
  amy/templates/reports/duplicate_training_requests.html
  amy/templates/requests/trainingrequests_merge.html
  amy/templates/workshops/action_required_privacy.html
  amy/templates/workshops/events_merge.html
  amy/templates/workshops/person.html
  amy/templates/workshops/person_bulk_add_results.html
  amy/templates/workshops/persons_merge.html
  amy/workshops/forms.py
  amy/workshops/migrations/0221_auto_20201025_1113.py
  amy/workshops/mixins.py
  amy/workshops/models.py
  amy/workshops/templatetags/links.py
Labels: component: database (DB), component: security, component: user interface (UI)
