Repository carpentries/amy, pull requests merged in 2020-11, with the labels that each got.

#1732 fix typo from ubmission to Submission
  amy/templates/mailing/training_request.txt
Labels: component: user interface (UI)

#1735 specify request form is for centrally org. wkshp
  amy/templates/forms/workshop_landing.html
  amy/templates/forms/workshoprequest.html
Labels: component: user interface (UI)

#1737 moves workshop public question to more prominent place on page
  amy/templates/includes/event_details_table.html
  amy/workshops/forms.py
Labels: component: user interface (UI)

#1739 Make docs more accessible
  .gitignore
  Makefile
  docs/PyData_deploy.md
  docs/design/database_models.md
  docs/design/index.md
  docs/design/template_hierarchy.md
  docs/index.md
  docs/procedures.md
  docs/sending_mails.md
  docs/user_guide.md
  mkdocs.yml
  requirements.txt
Labels: component: documentation

#1712 Acknowledge Workshop Request review
  Makefile
  amy/api/serializers.py
  amy/api/urls.py
  amy/api/views.py
  amy/autoemails/actions.py
  amy/autoemails/base_views.py
  amy/autoemails/fixtures/templates_triggers.json
  amy/autoemails/forms.py
  amy/autoemails/migrations/0014_auto_20201025_1846.py
  amy/autoemails/models.py
  amy/autoemails/tests/test_genericaction.py
  amy/autoemails/tests/test_recruithelpersaction.py
  amy/autoemails/tests/test_views.py
  amy/autoemails/urls.py
  amy/autoemails/views.py
  amy/extforms/forms.py
  amy/extforms/views.py
  amy/extrequests/views.py
  amy/static/amy_utils.js
  amy/static/css/amy.css
  amy/templates/includes/requests_bottom_action_btns.html
  amy/templates/includes/template_response.html
  amy/templates/requests/workshoprequest.html
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0221_workshoprequest_rq_jobs.py
  amy/workshops/models.py
  config/urls.py
  docker-compose.yml
Labels: component: email automation, component: user interface (UI), type: new feature

#1741 Workshop listed - question on WRFs
  amy/extforms/tests/test_selforganised_submission_form.py
  amy/extforms/tests/test_workshop_inquiry_form.py
  amy/extforms/tests/test_workshop_request_form.py
  amy/extrequests/forms.py
  amy/extrequests/migrations/0025_auto_20201105_1949.py
  amy/extrequests/views.py
  amy/templates/includes/selforganisedsubmission_details.html
  amy/templates/includes/workshopinquiry_details.html
  amy/templates/includes/workshoprequest_details.html
  amy/templates/mailing/selforganisedsubmission.txt
  amy/templates/mailing/selforganisedsubmission_admin.txt
  amy/templates/mailing/workshopinquiry.txt
  amy/templates/mailing/workshopinquiry_admin.txt
  amy/templates/mailing/workshoprequest.txt
  amy/templates/mailing/workshoprequest_admin.txt
  amy/workshops/migrations/0222_workshoprequest_workshop_listed.py
  amy/workshops/models.py
Labels: component: database (DB), component: forms, component: user interface (UI), priority: essential

#1742 Self-Organised Submissions: start, end date fields.
  amy/extforms/tests/test_selforganised_submission_form.py
  amy/extrequests/forms.py
  amy/extrequests/migrations/0026_auto_20201107_1428.py
  amy/extrequests/models.py
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/extrequests/views.py
  amy/templates/includes/selforganisedsubmission_details.html
  amy/templates/mailing/selforganisedsubmission.txt
  amy/templates/mailing/selforganisedsubmission_admin.txt
  amy/workshops/models.py
Labels: component: database (DB), component: forms, component: user interface (UI)

#1743 Enforce learner for seat open/member task
  amy/workshops/models.py
  amy/workshops/tests/test_tasks.py
Labels: type: enhancement

#1744 Automatically check "TTT Open applications" when TTT tag is selected
  amy/static/amy_utils.js
Labels: component: user interface (UI), javascript, type: new feature

#1746 Prefill WRF accept and create a new event form
  amy/extrequests/base_views.py
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/extrequests/tests/test_wrfinitial.py
  amy/extrequests/views.py
  amy/workshops/forms.py
  amy/workshops/models.py
Labels: component: forms, component: user interface (UI), type: new feature

#1748 Extend AskForWebsite with supporting instructor role
  amy/autoemails/actions.py
  amy/autoemails/tests/test_askforwebsiteaction.py
Labels: component: email automation, type: enhancement
