Repository carpentries/amy, pull requests merged in 2021-08, with the labels that each got.

#2010 [#1936] Membership: edit rolled values
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
Labels: type: new feature

#2012 [#1931] Prepopulate workshop and public training seats based on selected membership variant
  amy/fiscal/forms.py
  amy/static/membership_create.js
Labels: component: user interface (UI)

#2017 [#2014] Fix: redirect if only 1 group of results is singular
  amy/dashboard/tests/test_search.py
  amy/dashboard/views.py
Labels: priority: essential, type: bug

#2013 feat(Consents): Updated Merge person to handle new consents.
  amy/api/tests/test_api_structure.py
  amy/api/tests/test_filter.py
  amy/dashboard/views.py
  amy/templates/workshops/persons_merge.html
  amy/workshops/forms.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_person.py
  amy/workshops/tests/test_util.py
  amy/workshops/util.py
  amy/workshops/views.py
Labels: component: forms, python

#1994 Alacarte membership
  amy/workshops/migrations/0249_auto_20210709_1542.py
  amy/workshops/models.py
Labels: component: database (DB)

#2028 [#1999] Change Training Progress "a" state badge color
  amy/templates/trainings/all_trainees.html
  amy/workshops/templatetags/training_progress.py
Labels: component: user interface (UI)

#2029 [#1899][#1907][#1983] Bunch of small fixes to Workshop Request forms
  amy/extrequests/migrations/0029_auto_20210807_1951.py
  amy/extrequests/models.py
  amy/templates/forms/workshopinquiry.html
  amy/templates/forms/workshoprequest.html
  amy/templates/mailing/workshopinquiry.html
  amy/templates/mailing/workshopinquiry.txt
  amy/templates/mailing/workshoprequest.html
  amy/templates/mailing/workshoprequest.txt
  amy/workshops/migrations/0250_auto_20210807_1951.py
  amy/workshops/models.py
Labels: component: user interface (UI), component: forms

#2035 [#2000] "Seats exceeded" warning
  amy/extrequests/forms.py
  amy/extrequests/tests/test_training_request.py
  amy/extrequests/views.py
  amy/workshops/models.py
  amy/workshops/tests/test_tasks.py
  amy/workshops/views.py
Labels: priority: essential

#2036 [#2005] Membership Extend: use new end date instead of number of days
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
  amy/static/membership_extend.js
Labels: component: user interface (UI)

#2020 [#2015] Edit membership extensions
  amy/fiscal/fields.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
  amy/static/css/amy.css
  config/settings.py
Labels: component: user interface (UI), type: new feature, component: forms

#2009 [#1929] Log membership members change
  amy/fiscal/tests/test_membership_members.py
  amy/fiscal/views.py
  amy/workshops/management/commands/sync_usersocialauth.py
  amy/workshops/receivers.py
Labels: type: new feature

#2031 Fix(Consents): Fix email reply to.
  amy/autoemails/actions.py
  amy/autoemails/fixtures/templates_triggers.json
  amy/autoemails/models.py
  amy/autoemails/tests/test_newconsentrequiredaction.py
Labels: type: bug, python, component: email automation
