Repository carpentries/amy, pull requests merged in 2021-07, with the labels that each got.

#1997 [#1996] Fix *CountriesFilter override countries
  amy/workshops/filters.py
  amy/workshops/tests/test_filters.py
Labels: priority: essential, type: bug

#1998 [#1946] Fix: warning msg for exceeding remaining seats
  amy/extrequests/tests/test_training_request.py
  amy/extrequests/views.py
Labels: priority: essential, type: bug

#2002 fix(Consents): Trainee dashboard user edit page updates consents correctly.
  amy/consents/forms.py
  amy/consents/tests/test_action_required_view.py
  amy/dashboard/forms.py
  amy/dashboard/tests/test_autoupdate_profile.py
  amy/dashboard/views.py
  amy/templates/dashboard/autoupdate_profile.html
Labels: component: forms, python, type: bug

#1990 [#1875] update `procedures.md`
  amy/__init__.py
  amy/workshops/__init__.py
  amy/workshops/context_processors.py
  docs/procedures.md
Labels: component: deployment, component: documentation, type: maintenance

#1985 feat(Consents): Remove old actions required form.
  amy/api/tests/test_api_structure.py
  amy/api/tests/test_export.py
  amy/api/tests/test_filter.py
  amy/api/tests/test_trainingrequests.py
  amy/consents/tests/test_action_required_view.py
  amy/dashboard/tests/test_autoupdate_profile.py
  amy/dashboard/tests/test_landing_page.py
  amy/dashboard/tests/test_trainee_dashboard.py
  amy/extcomments/tests.py
  amy/templates/workshops/action_required_privacy.html
  amy/workshops/action_required.py
  amy/workshops/forms.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_action_required.py
  amy/workshops/tests/test_person.py
  amy/workshops/tests/test_security.py
  amy/workshops/urls.py
  amy/workshops/views.py
  config/settings.py
Labels: component: API, component: forms, python

#2006 [#1942][#1943] List events on membership page, display event type of organization page
  amy/fiscal/tests/test_organization.py
  amy/fiscal/views.py
  amy/templates/fiscal/membership.html
  amy/templates/fiscal/organization.html
Labels: component: user interface (UI)

#2007 [#1938] Add comment to membership extension
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
Labels: component: forms, component: user interface (UI), type: enhancement

#2008 [#1934][#1935] Membership Rollover form: remove default agreement link, move "Copy ...?" fields up
  amy/fiscal/forms.py
  amy/fiscal/views.py
Labels: component: forms, component: user interface (UI), type: enhancement

#2011 [#1928] Confirm member removal
  amy/fiscal/forms.py
  amy/static/member_form.js
Labels: component: user interface (UI)
