Repository carpentries/amy, pull requests merged in 2021-10, with the labels that each got.

#2057 [#2055] Fix wrong template variable displayed in Organization page
  amy/templates/fiscal/organization.html
Labels: type: bug, component: user interface (UI)

#2071 [#2056] Fix for negative remaining values when rolling over
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
Labels: type: bug

#2058 [#2051] Membership counting queryset adjustment
  amy/fiscal/tests/test_membership.py
  amy/workshops/models.py
Labels: type: bug

#2073 tweak privacy language on consent page
  amy/templates/consents/action_required_terms.html
Labels: component: user interface (UI), component: law compliance
