Repository carpentries/amy, pull requests merged in 2021-04, with the labels that each got.

#1876 Small improvements and security fixes
  .editorconfig
  .github/workflows/codeql-analysis.yml
  .travis.yml
  amy/workshops/management/commands/check_for_workshop_websites_updates.py
  amy/workshops/util.py
  amy/workshops/views.py
Labels: type: maintenance

#1871 [#1854][#1855][#1856] Adjustments to rolling-over mechanism, display person membership roles
  amy/dashboard/views.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
  amy/templates/dashboard/trainee_dashboard.html
  amy/templates/workshops/person.html
  amy/workshops/views.py
Labels: component: user interface (UI), python, type: enhancement

#1860 feature(Consents): Users prompted to sign new required terms on login.
  amy/consents/forms.py
  amy/consents/middleware.py
  amy/consents/migrations/0001_squashed_0002_auto_20210314_1928.py
  amy/consents/models.py
  amy/consents/tests/test_action_required_view.py
  amy/consents/tests/test_forms.py
  amy/consents/tests/test_models.py
  amy/consents/tests/test_util.py
  amy/consents/urls.py
  amy/consents/util.py
  amy/consents/views.py
  amy/templates/consents/action_required_terms.html
  amy/workshops/management/commands/fake_database.py
  amy/workshops/views.py
  config/settings.py
Labels: component: user interface (UI), python, type: new feature

#1863 Preapproved registration
  amy/templates/mailing/training_request.html
  amy/templates/mailing/training_request.txt
  amy/workshops/migrations/0240_auto_20210402_1917.py
  amy/workshops/models.py
Labels: component: user interface (UI), status: needs improvements

#1893 ref(README): Changed setup instructions ordering
  README.md
Labels: component: documentation

#1880 feature(Consents): Store unset consents when term or person is created
  amy/consents/admin.py
  amy/consents/apps.py
  amy/consents/forms.py
  amy/consents/migrations/0002_auto_20210401_1744.py
  amy/consents/models.py
  amy/consents/signals.py
  amy/consents/tests/helpers.py
  amy/consents/tests/test_action_required_view.py
  amy/consents/tests/test_forms.py
  amy/consents/tests/test_models.py
  amy/consents/tests/test_signals.py
  amy/consents/tests/test_util.py
  amy/consents/tests/test_views.py
  amy/workshops/management/commands/fake_database.py
Labels: component: database (DB), python, type: new feature

#1862 ref(consent): Add helptext to Terms.
  amy/consents/forms.py
  amy/consents/migrations/0003_term_help_text.py
  amy/consents/models.py
  amy/workshops/management/commands/fake_database.py
Labels: component: user interface (UI), python, type: new feature

#1885 feature(Consents): Archive terms and term options from Django Admin view
  amy/consents/admin.py
  amy/consents/models.py
  amy/consents/tests/test_models.py
  amy/templates/consents/admin_change_form_term.html
  amy/workshops/management/commands/fake_database.py
Labels: component: user interface (UI), python, type: new feature

#1872 feature(Consents): Email user when there is a new required consent to approve.
  amy/autoemails/actions.py
  amy/autoemails/base_views.py
  amy/autoemails/fixtures/templates_triggers.json
  amy/autoemails/migrations/0015_auto_20210405_1920.py
  amy/autoemails/models.py
  amy/consents/admin.py
  amy/consents/migrations/0004_term_rq_jobs.py
  amy/consents/models.py
Labels: component: database (DB), component: email automation, python

#1896 feature(Consents): Add Existing terms to the consents models in a migration.
  amy/consents/migrations/0005_auto_20210411_2325.py
  amy/consents/tests/base.py
  amy/consents/tests/helpers.py
  amy/consents/tests/test_action_required_view.py
  amy/consents/tests/test_forms.py
  amy/consents/tests/test_models.py
  amy/consents/tests/test_signals.py
  amy/consents/tests/test_util.py
  amy/consents/tests/test_views.py
  amy/workshops/management/commands/fake_database.py
Labels: component: database (DB), python

#1900 feat(Consents): Added documentation notes about the database tables.
  docs/amy_database_structure.md
Labels: component: documentation

#1902 [#1759] Self-organised Submission form URL warnings + JS validation
  amy/extrequests/forms.py
  amy/static/selforganisedsubmission_form.js
Labels: component: forms, javascript, type: enhancement

#1903 [#1898] Fix django messages tags
  config/settings.py
Labels: component: user interface (UI), type: bug

#1905 feat(Profile Archival): Archive person profile.
  amy/templates/dashboard/trainee_dashboard.html
  amy/templates/workshops/person.html
  amy/workshops/base_views.py
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
  amy/workshops/urls.py
  amy/workshops/views.py
Labels: component: API, component: user interface (UI), python

#1910 [#1711] Reactivate instructor survey links
  amy/templates/includes/event_details_table.html
  amy/workshops/forms.py
Labels: component: forms, component: user interface (UI)

#1911 fix(Consents): Fixed issue with admin term and term option add being broken.
  amy/consents/admin.py
  amy/consents/models.py
  amy/consents/tests/test_models.py
  amy/templates/consents/admin_change_form_term.html
Labels: component: API, component: user interface (UI)

#1820 feature: Add ask to repeat TrainingProgress status
  amy/api/tests/test_export.py
  amy/api/urls.py
  amy/api/views.py
  amy/dashboard/tests/test_trainee_dashboard.py
  amy/templates/workshops/event_edit_form.html
  amy/trainings/tests/test_trainees.py
  amy/trainings/tests/test_training_progress.py
  amy/workshops/forms.py
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0241_add_ask_to_repeat_to_training_progress_status.py
  amy/workshops/models.py
  amy/workshops/templatetags/training_progress.py
  amy/workshops/tests/test_person.py
  amy/workshops/views.py
Labels: component: API, component: forms
