Repository carpentries/amy, pull requests merged in 2021-05, with the labels that each got.

#1908 feat(Profile Archival): All consents are unset when a person is archived.
  amy/consents/apps.py
  amy/consents/models.py
  amy/consents/receivers.py
  amy/consents/tests/base.py
  amy/consents/tests/test_models.py
  amy/workshops/apps.py
  amy/workshops/models.py
  amy/workshops/receivers.py
  amy/workshops/signals/__init__.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_person.py
  amy/workshops/views.py
Labels: component: API, component: database (DB), python

#1916 feature(Profile Archival): Added an info message when the user's profile is not active
  amy/workshops/views.py
Labels: component: user interface (UI), python

#1922 fix(Profile Archival): Remove more personal information when the user is archived.
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
Labels: component: API, python

#1919 feature(Profile Archival): Remove profile change history.
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
Labels: component: database (DB), type: new feature

#1921 feature(Profile Archival): Remove groups and permissions from the user when the profile is archived.
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
Labels: python, type: new feature

#1924 [#1879] Add "Withdrawn" state to TrainingRequest
  amy/workshops/migrations/0242_auto_20210503_1359.py
  amy/workshops/mixins.py
  amy/workshops/models.py
  amy/workshops/templatetags/state.py
Labels: component: database (DB), component: user interface (UI), type: enhancement

#1947 [#1946] Fix BulkMatchTrainingRequestForm
  amy/extrequests/forms.py
  amy/extrequests/tests/test_training_request.py
Labels: component: forms, type: bug

#1948 [#1939] Make affiliated organisations symmetrical
  amy/fiscal/tests/test_organization.py
  amy/workshops/migrations/0243_auto_20210508_1954.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), type: bug

#1949 [#1945] Change Membership public status def. value
  amy/workshops/migrations/0228_auto_20210204_0658.py
  amy/workshops/migrations/0237_auto_20210321_1056.py
Labels: component: database (DB), type: bug

#1950 [#1944] Make comments work w/o user's email
  amy/extcomments/forms.py
  amy/extcomments/tests.py
  amy/extcomments/utils.py
Labels: component: forms, type: bug

#1953 [#1940] Fix display of membership training seats
  amy/templates/fiscal/membership.html
Labels: component: user interface (UI), type: bug

#1952 [#1930] Distinct membership members, person tasks
  amy/fiscal/base_views.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership_members.py
  amy/fiscal/tests/test_membership_tasks.py
  amy/fiscal/views.py
  amy/templates/fiscal/membership_formset.html
  amy/workshops/migrations/0244_auto_20210509_2051.py
  amy/workshops/models.py
Labels: component: database (DB), component: forms, component: user interface (UI), type: bug

#1954 [#1937] Multiple membership extensions
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
  amy/templates/fiscal/membership.html
  amy/workshops/migrations/0245_membership_extensions.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI)

#1917 feature(Profile Archival): Added Archived_at to person model and display on person details page.
  amy/consents/models.py
  amy/templates/workshops/person.html
  amy/workshops/migrations/0246_person_archived_at.py
  amy/workshops/mixins.py
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
Labels: component: database (DB), component: user interface (UI), type: new feature

#1923 feature(Profile Archival): Added social auth removal to Person archive.
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
Labels: python, type: new feature

#1959 [#1941] Link events with memberships
  amy/fiscal/tests/test_membership.py
  amy/templates/includes/event_details_table.html
  amy/workshops/forms.py
  amy/workshops/migrations/0247_event_membership.py
  amy/workshops/models.py
  amy/workshops/views.py
Labels: component: database (DB), component: user interface (UI)

#1956 [#1932][#1933] Link rolled-over memberships
  amy/fiscal/base_views.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
  amy/templates/fiscal/membership.html
  amy/workshops/migrations/0248_membership_rolled_to_membership.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), type: enhancement
