Repository carpentries/amy, pull requests merged in 2021-02, with the labels that each got.

#1783 Cleanup files dirs
  .dockerignore
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .gitignore
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  Dockerfile
  README.md
  amy/workshops/migrations/0097_auto_20160519_0739.py
  amy/workshops/migrations/0139_fix_language_names.py
  amy/workshops/migrations/0178_auto_20190213_1640.py
  amy/workshops/migrations/data/registry.json
  config/settings.py
  docker-compose.yml
  docker/Dockerfile
  docker/docker-compose.yml
  docs/acknowledgements.md
  docs/authors.md
  docs/database/postgresql_scaffolding.sql
  logs/.dummy
  package.json
Labels: type: maintenance

#1785 Memberships: simple fields
  amy/fiscal/filters.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/templates/fiscal/membership.html
  amy/templates/navigation.html
  amy/workshops/migrations/0228_auto_20210204_0658.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), type: enhancement

#1793 [#1792] assigned to: Distinct list of users
  amy/dashboard/forms.py
  amy/dashboard/tests/test_assignment_form.py
Labels: priority: essential, type: bug

#1786 Memberships: change Organization relationship from FK to M2M
  .pre-commit-config.yaml
  amy/dashboard/tests/test_search.py
  amy/fiscal/filters.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/urls.py
  amy/fiscal/views.py
  amy/static/amy_utils.js
  amy/templates/fiscal/all_memberships.html
  amy/templates/fiscal/membership.html
  amy/templates/fiscal/membership_members.html
  amy/workshops/admin.py
  amy/workshops/base_views.py
  amy/workshops/lookups.py
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0229_membership_M2M_organisations.py
  amy/workshops/models.py
  amy/workshops/tests/test_tasks.py
  config/settings.py
  dev_requirements.txt
  pyproject.toml
  requirements.txt
Labels: component: database (DB), component: user interface (UI), javascript

#1795 [#1775] Person roles for Memberships
  .pre-commit-config.yaml
  amy/fiscal/admin.py
  amy/fiscal/forms.py
  amy/fiscal/migrations/0001_initial.py
  amy/fiscal/models.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/tests/test_membership_tasks.py
  amy/fiscal/urls.py
  amy/fiscal/views.py
  amy/templates/fiscal/membership.html
  amy/templates/fiscal/membership_formset.html
  amy/workshops/migrations/0230_membership_persons.py
  amy/workshops/models.py
Labels: component: database (DB), component: forms, component: user interface (UI)

#1799 [#1796] Fix small mixups on Memberhips formsets
  amy/fiscal/forms.py
  amy/fiscal/views.py
  amy/workshops/lookups.py
Labels: type: bug

#1800 [#1797] Fix small issues with organisations
  amy/fiscal/views.py
  amy/templates/fiscal/all_organizations.html
  amy/templates/fiscal/organization.html
Labels: type: bug

#1802 fix: Update main branch name after transition from master
  .github/CONTRIBUTING.md
  .github/workflows/build-docs.yml
  README.md
  docs/procedures.md
Labels: component: documentation

#1803 fix: Change help text for event country.
  amy/workshops/migrations/0231_auto_20210217_2055.py
  amy/workshops/models.py
Labels: component: database (DB)

#1789 add in new membership fields
  docs/amy_database_structure.md
Labels: component: documentation

#1805 feature: Dashboard events filtered to logged in user by default.
  amy/dashboard/tests/test_landing_page.py
  amy/dashboard/views.py
  amy/workshops/models.py
Labels: component: forms, component: user interface (UI)

#1813 feature: Add language to instructor training application about sharing data
  amy/workshops/models.py
Labels: component: forms

#1810 [#1798] Membership name, default organisation
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
  amy/static/membership_create.js
  amy/templates/fiscal/all_memberships.html
  amy/templates/fiscal/membership.html
  amy/workshops/lookups.py
  amy/workshops/migrations/0065_multiple_memberships.py
  amy/workshops/migrations/0229_membership_M2M_organisations.py
  amy/workshops/migrations/0232_membership_name.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), type: new feature

#1809 Docs db tables
  docs/amy_database_structure.md
Labels: component: documentation

#1806 feature: Filter workshop staff by knowledge domain.
  amy/workshops/filters.py
  amy/workshops/forms.py
  amy/workshops/lookups.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_workshop_staff_searching.py
Labels: component: forms, component: user interface (UI)
