Repository carpentries/amy, pull requests merged in 2021-06, with the labels that each got.

#1966 [#1875] Add linter GitHub action
  .github/workflows/linter.yml
Labels: type: maintenance

#1971 fix(Consent): Remove old-style consents from trainee dashboard.
  amy/dashboard/views.py
  amy/templates/dashboard/trainee_dashboard.html
Labels: component: user interface (UI)

#1970 fix(Consent): Remove old style consents from filter
  amy/api/filters.py
  amy/api/tests/test_filter.py
  amy/consents/models.py
Labels: component: API

#1978 [#1976] Linters configuration paths (GitHub CI)
  .github/workflows/linter.yml
Labels: type: bug

#1980 Fix non-unique membership members in dev database
  amy/workshops/management/commands/fake_database.py
Labels: type: bug

#1981 add note about superuser created by default
  README.md
Labels: component: documentation

#1975 fix(Consents) Changed the person data view and serializers to only show the active consents
  amy/api/serializers.py
  amy/api/tests/test_api_structure.py
  amy/api/tests/test_export.py
Labels: component: API, priority: essential

#1965 [#1875] Pipenv instead of requirements.txt
  .github/workflows/python-test.yml
  .pre-commit-config.yaml
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  dev_requirements.txt
  docker/Dockerfile
  requirements.txt
Labels: component: documentation, type: maintenance

#1984 feat(Consents): Migrating old consent data to new consents
  amy/consents/migrations/0006_auto_20210614_1234.py
Labels: component: database (DB)
