Repository carpentries/amy, pull requests merged in 2021-03, with the labels that each got.

#1816 [#1776][#1777] "Extend" membership
  amy/fiscal/base_views.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/urls.py
  amy/fiscal/views.py
  amy/static/membership_extend.js
  amy/templates/fiscal/membership.html
  amy/templates/fiscal/organization.html
  amy/workshops/migrations/0233_membership_extended.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), javascript, python

#1817 [#1778][#1779] Membership rollover workshops and seats
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/urls.py
  amy/fiscal/views.py
  amy/templates/fiscal/membership.html
  amy/templates/fiscal/organization.html
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0234_auto_20210228_0940.py
  amy/workshops/models.py
Labels: component: database (DB), component: user interface (UI), python

#1821 [#1819] Fix search for single result
  amy/dashboard/forms.py
  amy/dashboard/tests/test_search.py
  amy/dashboard/views.py
Labels: priority: essential, python, type: bug

#1815 bugfix: Removed initial slug value from WRFInitial.
  amy/extrequests/base_views.py
  amy/extrequests/tests/test_wrfinitial.py
Labels: component: forms

#1824 [#1781] Discounted workshops
  amy/fiscal/tests/test_membership.py
  amy/templates/fiscal/membership.html
  amy/templates/fiscal/organization.html
  amy/workshops/models.py
Labels: component: user interface (UI), python, type: new feature

#1825 minor formatting fix
  docs/amy_database_structure.md
Labels: component: documentation

#1837 #1833 - event sponsorship
  amy/extrequests/tests/test_selforganised_submissions.py
  amy/extrequests/tests/test_workshop_inquiries.py
  amy/extrequests/tests/test_workshop_requests.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/tests/test_sponsorship.py
  amy/fiscal/urls.py
  amy/fiscal/views.py
  amy/templates/fiscal/organization.html
  amy/templates/includes/event_details_table.html
  amy/templates/workshops/event.html
  amy/templates/workshops/event_edit_form.html
  amy/workshops/forms.py
  amy/workshops/migrations/0235_remove_event_sponsors.py
  amy/workshops/models.py
  amy/workshops/tests/test_event.py
  amy/workshops/views.py
  docs/design/database_models.md
  docs/models_in_applications.md
Labels: component: database (DB), component: documentation, component: user interface (UI), python, type: maintenance, type: new feature

#1832 feature(Consents): Create Consent App and base models.
  amy/consents/__init__.py
  amy/consents/admin.py
  amy/consents/apps.py
  amy/consents/forms.py
  amy/consents/migrations/0001_initial.py
  amy/consents/migrations/__init__.py
  amy/consents/models.py
  amy/consents/tests/__init__.py
  amy/consents/tests/test_models.py
  amy/consents/urls.py
  config/settings.py
  config/urls.py
Labels: component: database (DB), type: new feature

#1839 [#1834] Organisation coordinates
  amy/fiscal/forms.py
  amy/templates/fiscal/organization.html
  amy/workshops/migrations/0236_organization_coordinates.py
  amy/workshops/models.py
  docs/amy_database_structure.md
Labels: component: database (DB), component: user interface (UI), python

#1840 feat(Consents): Terms should be editable from Django admin view.
  amy/consents/admin.py
  amy/consents/migrations/0001_squashed_0002_auto_20210314_1928.py
  amy/consents/models.py
Labels: component: database (DB)

#1866 fix typo in documentation
  docs/amy_database_structure.md
Labels: component: documentation

#1857 [#1780][#1853][#1849][#1852][#1851] Membership calculations, UI improvements, fixes from feedback
  amy/dashboard/tests/test_search.py
  amy/dashboard/views.py
  amy/extrequests/forms.py
  amy/extrequests/views.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/tests/test_membership_tasks.py
  amy/fiscal/views.py
  amy/reports/views.py
  amy/templates/fiscal/all_memberships.html
  amy/templates/fiscal/membership.html
  amy/templates/fiscal/membership_formset.html
  amy/templates/fiscal/organization.html
  amy/templates/reports/membership_trainings_stats.html
  amy/templates/workshops/event.html
  amy/templates/workshops/event_edit_form.html
  amy/templates/workshops/person_edit_form.html
  amy/templates/workshops/task.html
  amy/workshops/forms.py
  amy/workshops/lookups.py
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0237_auto_20210321_1056.py
  amy/workshops/migrations/0238_task_seat_public.py
  amy/workshops/models.py
  amy/workshops/tests/test_tasks.py
  amy/workshops/views.py
  docs/amy_database_structure.md
Labels: component: database (DB), component: user interface (UI), python, type: enhancement

#1868 GH action to run tests
  .github/workflows/codeql-analysis.yml
  .github/workflows/python-test.yml
  config/settings.py
Labels: type: maintenance

#1858 [#1838][#1848][#1850] Improvements to Membership formsets
  amy/fiscal/forms.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/tests/test_membership_members.py
  amy/fiscal/tests/test_membership_tasks.py
  amy/static/amy_utils.js
  amy/static/css/amy.css
  amy/templates/fiscal/membership_formset.html
Labels: component: user interface (UI), javascript, python, type: enhancement

#1867 [#1835] Switch Organization.domain to accept domain + path
  amy/api/urls.py
  amy/api/views.py
  amy/fiscal/base_views.py
  amy/fiscal/forms.py
  amy/fiscal/tests/test_organization.py
  amy/fiscal/views.py
  amy/templates/dashboard/admin_dashboard.html
  amy/templates/dashboard/search.html
  amy/templates/fiscal/all_organizations.html
  amy/templates/fiscal/organization.html
  amy/templates/includes/event_details_table.html
  amy/templates/workshops/all_events.html
  amy/workshops/models.py
Labels: component: API, component: user interface (UI), python, type: enhancement

#1869 [#1836] Affiliated organisations
  amy/fiscal/forms.py
  amy/templates/fiscal/organization.html
  amy/workshops/migrations/0239_organization_affiliated_organizations.py
  amy/workshops/models.py
  docs/amy_database_structure.md
Labels: component: database (DB), component: user interface (UI)

#1864 assorted changes to trainee progress view
  amy/templates/dashboard/training_progress.html
Labels: component: user interface (UI)
