Repository carpentries/amy, pull requests merged in 2022-02, with the labels that each got.

#2127 [#2067] Upcoming Teaching Opportunities on instructor page
  .pre-commit-config.yaml
  amy/communityroles/models.py
  amy/communityroles/templatetags/__init__.py
  amy/communityroles/templatetags/communityroles.py
  amy/communityroles/tests/test_models.py
  amy/communityroles/tests/test_templatetags.py
  amy/consents/tests/test_action_required_view.py
  amy/dashboard/filters.py
  amy/dashboard/tests/test_filters.py
  amy/dashboard/tests/test_instructor_dashboard.py
  amy/dashboard/tests/test_landing_page.py
  amy/dashboard/tests/test_upcoming_teaching_opportunities.py
  amy/dashboard/urls.py
  amy/dashboard/views.py
  amy/templates/base_nav.html
  amy/templates/dashboard/autoupdate_profile.html
  amy/templates/dashboard/instructor_dashboard.html
  amy/templates/dashboard/training_progress.html
  amy/templates/dashboard/upcoming_teaching_opportunities.html
  amy/templates/includes/teaching_opportunity.html
  amy/templates/navigation_instructor_dashboard.html
  amy/workshops/base_views.py
  amy/workshops/models.py
  amy/workshops/tests/test_security.py
  config/urls.py
  docs/design/template_hierarchy.md
Labels: component: user interface (UI)

#2130 Some tests misusing assertTrue for comparisons fix
  amy/extrequests/tests/test_training_request.py
Labels: type: maintenance, python

#2126 Bugfix/2113 communityroles date range validation
  amy/communityroles/forms.py
  amy/communityroles/tests/test_community_role_form.py
Labels: type: bug, python

#2134 Typos
  amy/autoemails/migrations/0018_auto_20220218_1950.py
  amy/autoemails/models.py
  amy/workshops/tests/test_event.py
  amy/workshops/tests/test_tasks.py
Labels: component: user interface (UI)

#2112 Auto emails docs
  docs/users_guide/index.md
Labels: component: documentation

#2132 add link to help guides to menu
  amy/templates/navigation.html
  amy/templates/navigation_instructor_dashboard.html
Labels: component: user interface (UI)

#2133 Instructor training form text
  amy/extforms/views.py
  amy/templates/forms/trainingrequest.html
Labels: component: user interface (UI), component: forms

#2137 add submission date column to all WRF views
  amy/templates/requests/all_selforganisedsubmissions.html
  amy/templates/requests/all_workshopinquiries.html
  amy/templates/requests/all_workshoprequests.html
Labels: component: user interface (UI)
