Repository carpentries/amy, pull requests merged in 2022-05, with the labels that each got.

#2165 [#2069] Resign from recruitment
  amy/dashboard/tests/test_instructor_recruitment_views.py
  amy/dashboard/urls.py
  amy/dashboard/views.py
  amy/templates/dashboard/upcoming_teaching_opportunities.html
Labels: type: new feature

#2177 [#2078] Maintenance: update Django to version 3.2 LTS
  Pipfile
  Pipfile.lock
  amy/autoemails/utils.py
  amy/consents/tests/test_views.py
  amy/extcomments/forms.py
  amy/extrequests/tests/test_training_request.py
  amy/fiscal/tests/test_membership.py
  amy/fiscal/views.py
  amy/workshops/base_views.py
  amy/workshops/lookups.py
  amy/workshops/signals/__init__.py
  amy/workshops/tests/test_tasks.py
  amy/workshops/util.py
  amy/workshops/views.py
  config/settings.py
Labels: type: maintenance

#2178 [#2082] Admin signs up Instructor on their behalf
  Pipfile.lock
  amy/recruitment/forms.py
  amy/recruitment/tests/test_forms.py
  amy/recruitment/tests/test_instructor_recruitment_views.py
  amy/recruitment/urls.py
  amy/recruitment/views.py
  amy/templates/includes/instructorrecruitment.html
  amy/templates/recruitment/instructorrecruitment_add_signup.html
  amy/workshops/lookups.py
Labels: component: user interface (UI), component: forms

#2151 Training search
  amy/dashboard/views.py
Labels: component: database (DB)

#2152 make new membership start day after previous ends
  amy/fiscal/forms.py
  amy/fiscal/views.py
  amy/static/amy_utils.js
  amy/static/calendar_popup.js
Labels: type: bug, component: forms

#2179 [#2066] Close signups
  amy/autoemails/actions.py
  amy/autoemails/fixtures/templates_triggers.json
  amy/autoemails/migrations/0019_alter_trigger_action.py
  amy/autoemails/models.py
  amy/autoemails/tests/test_declinedinstructorsaction.py
  amy/autoemails/tests/test_instructorshostintroductionaction.py
  amy/dashboard/views.py
  amy/recruitment/migrations/0004_auto_20220526_0617.py
  amy/recruitment/models.py
  amy/recruitment/tests/test_instructor_recruitment_views.py
  amy/recruitment/urls.py
  amy/recruitment/views.py
  amy/static/css/amy.css
  amy/templates/dashboard/instructor_dashboard.html
  amy/templates/includes/instructorrecruitment.html
  amy/templates/recruitment/instructorrecruitment_list.html
  amy/workshops/views.py
Labels: type: new feature, component: forms

#2182 [#2153][#2154] Recruitment event requirements (date in future + location data)
  amy/autoemails/tests/test_askforwebsiteaction.py
  amy/autoemails/tests/test_instructorshostintroductionaction.py
  amy/autoemails/tests/test_newinstructoraction.py
  amy/autoemails/tests/test_newsupportinginstructoraction.py
  amy/autoemails/tests/test_postworkshopaction.py
  amy/autoemails/tests/test_recruithelpersaction.py
  amy/autoemails/tests/test_selforganisedrequestaction.py
  amy/dashboard/tests/test_instructor_recruitment_views.py
  amy/dashboard/views.py
  amy/recruitment/tests/test_instructor_recruitment_views.py
  amy/recruitment/views.py
  amy/templates/includes/instructor_selection_summary.html
  amy/templates/recruitment/instructorrecruitment_add.html
  amy/workshops/models.py
  amy/workshops/tests/test_event.py
  amy/workshops/views.py
Labels: type: new feature

#2184 [#1875] No django-compressor, whitenoise instead
  .github/workflows/python-test.yml
  Pipfile
  Pipfile.lock
  amy/templates/base.html
  amy/templates/dashboard/admin_dashboard.html
  config/settings.py
  docker/Dockerfile
Labels: type: maintenance, component: user interface (UI), javascript
