Repository carpentries/amy, pull requests merged in 2023-07, with the labels that each got.

#2448 Improve scheduled email views
  amy/emails/actions.py
  amy/emails/controller.py
  amy/emails/forms.py
  amy/emails/migrations/0002_auto_20230703_2116.py
  amy/emails/models.py
  amy/emails/tests/actions/test_persons_merged.py
  amy/emails/tests/test_controller.py
  amy/emails/tests/test_models.py
  amy/emails/tests/test_views.py
  amy/emails/urls.py
  amy/emails/views.py
  amy/templates/emails/email_template_detail.html
  amy/templates/emails/email_template_list.html
  amy/templates/emails/scheduled_email_cancel.html
  amy/templates/emails/scheduled_email_detail.html
  amy/templates/emails/scheduled_email_edit.html
  amy/templates/emails/scheduled_email_header_details.html
  amy/templates/emails/scheduled_email_list.html
  amy/templates/emails/scheduled_email_reschedule.html
  amy/templates/navigation.html
Labels: type: new feature

#2466 Correct links in changes_log view
  amy/templates/workshops/changes_log.html
  amy/workshops/tests/test_views.py
Labels: type: bug, component: user interface (UI)

#2458 Add accessibility testing workflow
  .github/workflows/accessibility.yml
  .github/workflows/test.yml
  .gitignore
  .pa11yci
  README.md
  config/settings.py
  docs/accessibility_testing.md
  lighthouserc.js
  mkdocs.yml
  puppeteer-script.js
Labels: accessibility

#2487 Improvements to trainee progress view
  amy/dashboard/tests/test_instructor_dashboard.py
  amy/dashboard/tests/test_utils.py
  amy/dashboard/utils.py
  amy/dashboard/views.py
  amy/templates/dashboard/training_progress.html
  amy/templates/includes/progress_trainee_view.html
  amy/trainings/tests/test_template_tags.py
  amy/workshops/templatetags/training_progress.py
Labels: type: enhancement, component: user interface (UI)

#2490 Update color palette for better accessibility
  README.md
  amy/static/css/amy.css
  amy/static/css/custom_bootstrap.css.min.map
  amy/static/css/custom_bootstrap.min.css
  amy/static/css/custom_bootstrap.min.css.map
  amy/static/scss/custom_bootstrap.scss
  amy/templates/base.html
  package-lock.json
  package.json
Labels: accessibility
