Repository carpentries/amy, pull requests merged in 2023-06, with the labels that each got.

#2430 Allow longer auth tokens for password reset
  config/urls.py
Labels: type: bug

#2431 Create "Get Involved" requirement and associated Involvement model
  .github/workflows/test.yml
  Makefile
  amy/api/serializers.py
  amy/api/tests/test_export.py
  amy/consents/models.py
  amy/scripts/seed_involvements.py
  amy/scripts/seed_training_requirements.py
  amy/static/amy_utils.js
  amy/static/trainingprogress_form.js
  amy/trainings/admin.py
  amy/trainings/forms.py
  amy/trainings/migrations/0001_initial_create_involvement.py
  amy/trainings/models.py
  amy/trainings/tests/test_training_progress.py
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0260_add_involvement_types.py
  amy/workshops/migrations/0261_migrate_lesson_contribution_to_get_involved.py
  amy/workshops/mixins.py
  amy/workshops/models.py
  amy/workshops/templatetags/training_progress.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_migrations.py
  start.sh
Labels: component: user interface (UI), type: new feature, component: database (DB), component: API

#2444 Update instructor eligibility requirements with Get Involved step
  amy/dashboard/tests/test_instructor_dashboard.py
  amy/templates/includes/training_progresses_inline.html
  amy/trainings/forms.py
  amy/trainings/tests/test_trainees.py
  amy/trainings/tests/test_training_progress.py
  amy/workshops/models.py
  amy/workshops/tests/test_person.py
Labels: component: user interface (UI)

#2443 Update filter for unevaluated Get Involved step
  amy/trainings/filters.py
  amy/trainings/tests/test_filters.py
  amy/workshops/templatetags/training_progress.py
Labels: component: user interface (UI)

#2446 Update bulk training progress form to work with Get Involved step
  amy/trainings/forms.py
  amy/trainings/tests/test_trainees.py
Labels: component: user interface (UI)

#2453 Update trainee progress view
  amy/dashboard/forms.py
  amy/dashboard/tests/test_instructor_dashboard.py
  amy/dashboard/views.py
  amy/scripts/seed_involvements.py
  amy/templates/dashboard/training_progress.html
  amy/trainings/forms.py
  amy/trainings/tests/test_training_progress.py
  amy/workshops/models.py
Labels: component: user interface (UI), type: new feature, component: forms

#2447 Email module feature flag
  amy/emails/actions.py
  amy/emails/templatetags/__init__.py
  amy/emails/templatetags/emails.py
  amy/emails/tests/actions/test_feature_flag.py
  amy/emails/tests/actions/test_persons_merged.py
  amy/emails/tests/test_template_tags.py
  amy/emails/tests/test_views.py
  amy/emails/views.py
  amy/templates/navigation.html
  config/settings.py
Labels: type: new feature
