Repository carpentries/amy, pull requests merged in 2023-04, with the labels that each got.

#2369 update redis to >=4.5.4
  Pipfile
  Pipfile.lock
Labels: dependencies

#2363 Consents for training requests
  amy/consents/migrations/0008_trainingrequestconsent.py
  amy/consents/models.py
  amy/extforms/forms.py
  amy/extforms/tests/test_training_request_form.py
  amy/extrequests/forms.py
  amy/extrequests/tests/test_training_request.py
  amy/extrequests/views.py
  amy/static/css/amy.css
  amy/templates/includes/trainingrequest_details.html
  amy/templates/requests/trainingrequest.html
  amy/templates/requests/trainingrequests_merge.html
  amy/workshops/management/commands/create_superuser.py
Labels: component: user interface (UI), component: database (DB), component: forms

#2381 Set default filtering for training requests
  amy/extrequests/filters.py
  amy/extrequests/tests/test_training_request.py
Labels: type: bug, component: user interface (UI), type: optimization

#2375 Allow different term content on instructor training application
  amy/consents/admin.py
  amy/consents/migrations/0009_term_training_request_content.py
  amy/consents/models.py
  amy/extforms/forms.py
Labels: type: enhancement, component: user interface (UI), component: database (DB)

#2382 Add Titanium membership variant, remove prepopulation of membership benefits
  amy/fiscal/forms.py
  amy/static/membership_create.js
  amy/workshops/migrations/0257_alter_membership_variant.py
  amy/workshops/models.py
Labels: type: enhancement, component: user interface (UI), component: database (DB), component: forms

#2376 Display person consents when merging
  amy/templates/workshops/persons_merge.html
  amy/workshops/forms.py
  amy/workshops/tests/test_person.py
  amy/workshops/tests/test_utils.py
  amy/workshops/utils/consents.py
  amy/workshops/utils/merge.py
  amy/workshops/views.py
Labels: component: user interface (UI), component: forms

#2374 Update docs for consents
  CHANGELOG.md
  docs/amy_database_structure.md
  docs/design/database_models.md
  docs/design/projects/2021_consents.md
  docs/releases/README.md
  docs/users_guide/admin_index.md
Labels: component: documentation
