Repository carpentries/amy, pull requests merged in 2023-08, with the labels that each got.

#2492 Introduce separate views for Get Involved submissions
  amy/dashboard/tests/test_forms.py
  amy/dashboard/tests/test_get_involved_views.py
  amy/dashboard/tests/test_instructor_dashboard.py
  amy/dashboard/urls.py
  amy/dashboard/views.py
  amy/templates/dashboard/training_progress.html
  amy/templates/get_involved_form.html
  amy/templates/includes/progress_trainee_view.html
Labels: component: user interface (UI)

#2504 Add cancel button and fix validation bug on Get Involved form
  amy/dashboard/forms.py
  amy/dashboard/tests/test_forms.py
Labels: type: bug, component: user interface (UI)

#2505 [#2426] Hide Anymail errors
  amy/workshops/base_views.py
  config/settings.py
Labels: type: bug, component: forms

#2500 Set permissions for Get Involved views
  amy/dashboard/forms.py
  amy/dashboard/tests/test_forms.py
  amy/dashboard/tests/test_get_involved_views.py
  amy/dashboard/views.py
Labels: component: user interface (UI), component: security

#2502 Check that GitHub contributions are associated with a Carpentries GH organisation
  amy/api/tests/test_export.py
  amy/dashboard/forms.py
  amy/dashboard/tests/test_get_involved_views.py
  amy/dashboard/tests/test_instructor_dashboard.py
  amy/scripts/seed_involvements.py
  amy/templates/dashboard/training_progress.html
  amy/templates/get_involved_form.html
  amy/trainings/tests/test_filters.py
  amy/trainings/tests/test_trainees.py
  amy/trainings/tests/test_training_progress.py
  amy/workshops/models.py
Labels: component: user interface (UI)

#2510 Allow admins to submit/update training progress with non GitHub URL
  amy/api/tests/test_export.py
  amy/dashboard/forms.py
  amy/dashboard/tests/test_forms.py
  amy/trainings/tests/test_training_progress.py
  amy/workshops/migrations/0261_migrate_lesson_contribution_to_get_involved.py
  amy/workshops/models.py
Labels: type: bug, component: forms

#2512 Update conditions for progress messages at top of page
  amy/dashboard/tests/test_instructor_dashboard.py
  amy/templates/dashboard/training_progress.html
Labels: type: bug, component: user interface (UI)

#2513 Force HTTPS in `redirect_uri` generated by social auth
  config/settings.py
Labels: type: bug

#2515 Remove use of text-white to override text colour
  amy/templates/requests/all_trainingrequests.html
  amy/templates/workshops/workshop_staff.html
Labels: accessibility

#2506 [Emails] Scheduled email log author
  amy/emails/actions.py
  amy/emails/controller.py
  amy/emails/migrations/0004_scheduledemaillog_author.py
  amy/emails/models.py
  amy/emails/tests/actions/test_admin_signs_instructor_up_for_workshop.py
  amy/emails/tests/actions/test_instructor_badge_awarded.py
  amy/emails/tests/actions/test_instructor_confirmed_for_workshop.py
  amy/emails/tests/actions/test_instructor_declined_from_workshop.py
  amy/emails/tests/actions/test_instructor_signs_up_for_workshop.py
  amy/emails/tests/actions/test_persons_merged.py
  amy/emails/tests/test_controller.py
  amy/emails/tests/test_models.py
  amy/emails/tests/test_utils.py
  amy/emails/utils.py
  amy/emails/views.py
  amy/templates/emails/scheduled_email_detail.html
Labels: component: email automation

#2509 New checkout docs
  docs/users_guide/community_index.md
  docs/users_guide/images/checkout_complete.png
  docs/users_guide/images/get_involved_submit.png
  docs/users_guide/images/training_progress_menu.png
  docs/users_guide/images/training_progress_overview.png
  docs/users_guide/images/training_progress_overview_gi_pending.png
  docs/users_guide/images/training_progress_submit.png
  docs/users_guide/images/upcoming_teaching_opportunities.png
  docs/users_guide/images/workshop_intersted_signup.png
  mkdocs.yml
Labels: component: documentation

#2514 Update admin documentation for checkout
  docs/users_guide/admin_index.md
  docs/users_guide/images/all_trainees.png
  docs/users_guide/images/bulk_add_progress.png
  docs/users_guide/images/evaluate_get_involved_submission.png
  docs/users_guide/images/instructor_training_progress.png
  docs/users_guide/images/new_training_progress.png
  docs/users_guide/images/trainees_eligible_instructor.png
  docs/users_guide/images/trainees_menu.png
  docs/users_guide/images/trainees_with_unevaluated_submissions.png
Labels: component: documentation

#2518 Make GitHub organization check case insensitive
  amy/dashboard/forms.py
  amy/dashboard/tests/test_forms.py
Labels: type: bug, component: forms

#2464 Add documentation for checkout project and DB changes
  docs/amy_database_structure.md
  docs/design/database_models.md
  docs/design/projects/2023_instructor_checkout_changes.md
Labels: component: documentation

#2521 [Emails] Disable some notifications for non-admin users
  amy/dashboard/templatetags/__init__.py
  amy/dashboard/templatetags/notifications.py
  amy/dashboard/tests/test_template_tags.py
  amy/emails/tests/test_utils.py
  amy/emails/utils.py
  amy/templates/base.html
  config/settings.py
Labels: component: user interface (UI), component: forms

#2522 [Emails] Enable field `active` on EmailTemplates
  amy/emails/forms.py
  amy/emails/tests/test_controller.py
  amy/templates/emails/email_template_list.html
Labels: component: user interface (UI), component: forms

#2523 Remove question about learner count from WRF
  amy/autoemails/tests/test_views.py
  amy/extforms/tests/test_workshop_inquiry_form.py
  amy/extforms/tests/test_workshop_request_form.py
  amy/extrequests/forms.py
  amy/extrequests/migrations/0031_remove_workshopinquiryrequest_number_attendees.py
  amy/extrequests/models.py
  amy/extrequests/tests/test_workshop_inquiries.py
  amy/extrequests/tests/test_workshop_requests.py
  amy/extrequests/tests/test_wrfinitial.py
  amy/recruitment/tests/test_instructor_recruitment_views.py
  amy/templates/includes/workshopinquiry_details.html
  amy/templates/includes/workshoprequest_details.html
  amy/templates/mailing/workshopinquiry.txt
  amy/templates/mailing/workshopinquiry_admin.txt
  amy/templates/mailing/workshoprequest.txt
  amy/templates/mailing/workshoprequest_admin.txt
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0263_remove_workshoprequest_number_attendees.py
  amy/workshops/models.py
  amy/workshops/tests/test_migrations.py
  amy/workshops/tests/test_utils.py
Labels: component: database (DB), component: forms

#2519 Update release procedure documentation
  docs/manual_deployment_steps.md
  docs/procedures.md
  mkdocs.yml
Labels: component: deployment, component: documentation
