Repository carpentries/amy, pull requests merged in 2023-03, with the labels that each got.

#2354 Cache settings are now configurable via envvars
  config/settings.py
Labels: type: maintenance

#2335 Consents: Remove old terms from code
  Pipfile
  Pipfile.lock
  amy/__init__.py
  amy/api/filters.py
  amy/api/tests/test_filter.py
  amy/api/views.py
  amy/autoemails/tests/test_newinstructoraction.py
  amy/autoemails/tests/test_newsupportinginstructoraction.py
  amy/communityroles/models.py
  amy/consents/context_processors.py
  amy/consents/exceptions.py
  amy/consents/forms.py
  amy/consents/models.py
  amy/consents/templatetags/__init__.py
  amy/consents/templatetags/consents.py
  amy/consents/tests/base.py
  amy/consents/tests/test_action_required_view.py
  amy/consents/tests/test_forms.py
  amy/consents/tests/test_models.py
  amy/consents/tests/test_util.py
  amy/consents/tests/test_views.py
  amy/consents/util.py
  amy/dashboard/tests/test_autoupdate_profile.py
  amy/dashboard/views.py
  amy/extrequests/tests/test_training_request.py
  amy/extrequests/views.py
  amy/reports/views.py
  amy/templates/dashboard/instructor_dashboard.html
  amy/templates/workshops/all_tasks.html
  amy/templates/workshops/badge.html
  amy/templates/workshops/event.html
  amy/templates/workshops/event_edit_form.html
  amy/templates/workshops/workshop_staff.html
  amy/workshops/context_processors.py
  amy/workshops/filters.py
  amy/workshops/management/commands/fake_database.py
  amy/workshops/migrations/0256_auto_20230220_2051.py
  amy/workshops/models.py
  amy/workshops/tests/base.py
  amy/workshops/tests/test_person.py
  amy/workshops/views.py
  config/settings.py
  docs/amy_database_structure.md
Labels: type: enhancement, type: maintenance

#2358 fix 500 error after posting invalid community role
  amy/communityroles/fields.py
  amy/communityroles/tests/test_community_role_views.py
Labels: type: bug, component: user interface (UI)

#2346 Fix internal errors from filters
  amy/fiscal/filters.py
  amy/fiscal/tests/test_filters.py
  amy/fiscal/views.py
  amy/reports/views.py
  amy/templates/fiscal/all_memberships.html
  amy/templates/reports/membership_trainings_stats.html
  amy/workshops/models.py
Labels: type: enhancement, component: user interface (UI)

#2357 Colors for different builds
  amy/static/css/amy.css
  amy/templates/base.html
  amy/templates/navigation.html
  amy/workshops/context_processors.py
  config/settings.py
Labels: component: deployment, component: user interface (UI)

#2361 Reduce hardcoding of consent labels in UI
  amy/consents/admin.py
  amy/consents/migrations/0007_term_short_description.py
  amy/consents/models.py
  amy/dashboard/views.py
  amy/templates/dashboard/instructor_dashboard.html
  amy/workshops/views.py
  docs/amy_database_structure.md
  docs/users_guide/admin_index.md
  docs/users_guide/community_index.md
Labels: component: user interface (UI), component: database (DB)

#2366 Updated docs for server infrastructure and backups
  docs/design/cicd.md
  docs/design/database_backups.md
  docs/design/server_infrastructure.md
  mkdocs.yml
Labels: component: documentation
