Repository carpentries/amy, pull requests merged in 2024-10, with the labels that each got.

#2704 Automatically generate and update survey link
  amy/api/v2/serializers.py
  amy/templates/includes/event_details_table.html
  amy/workshops/forms.py
  amy/workshops/models.py
  amy/workshops/tests/test_event.py
Labels: type: enhancement

#2705 [#1992] Rename Host->Host Site, Sponsor->Organiser
  amy/templates/dashboard/admin_dashboard.html
  amy/templates/includes/event_details_table.html
  amy/templates/workshops/all_events.html
  amy/templates/workshops/events_merge.html
  amy/workshops/forms.py
Labels: component: user interface (UI), component: forms

#2595 Member codes docs
  amy/workshops/models.py
  docs/amy_database_structure.md
  docs/design/design_patterns.md
  docs/design/projects/2023_member_code_enforcement.md
  docs/manual_deployment_steps.md
  mkdocs.yml
Labels: component: documentation
