Repository carpentries/amy, pull requests merged in 2025-01, with the labels that each got.

#2733 Display tasks per role summary in instructor dashboard
  amy/dashboard/views.py
  amy/templates/dashboard/instructor_dashboard.html
Labels: component: user interface (UI)

#2734 Allow admins to see upcoming teaching opportunities
  amy/dashboard/tests/test_instructor_recruitment_views.py
  amy/dashboard/views.py
  amy/templates/dashboard/instructor_dashboard.html
  amy/templates/navigation.html
  amy/templates/navigation_instructor_dashboard.html
Labels: component: user interface (UI)

#2735 Update CICD workflow
  .github/workflows/cicd_develop.yml
Labels: component: deployment

#2716 Update upload-artifact version to v4
  .github/workflows/accessibility.yml
Labels: component: deployment

#2730 Updates admin user documentation about automated emails
  docs/users_guide/admin_index.md
  mkdocs.yml
Labels: component: documentation

#2747 API: Add `state_verbose` API r/o field to models that have state` field
  amy/api/v2/serializers.py
Labels: component: API

#2748 [Emails] Pretty-print JSON in scheduled email details
  amy/static/css/prism.css
  amy/static/prism.js
  amy/templates/base.html
  amy/templates/emails/scheduled_email_detail.html
  amy/workshops/templatetags/pprint.py
Labels: type: enhancement, component: user interface (UI), component: email automation

#2749 Remove missed columns with URL field for tasks
  amy/templates/workshops/event.html
  amy/templates/workshops/event_edit_form.html
Labels: type: bug, Getting started
